# Generated by Django 5.2.12 on 2026-04-29 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cliente_alter_produto_imagem'),
        ('produtos', '0002_alter_produto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
