# Generated by Django 5.2.12 on 2026-04-29 01:28

import produtos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['categoria', 'nome'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='ativo',
            new_name='disponivel',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('lanche', 'Lanche'), ('bebida', 'Bebida'), ('sobremesa', 'Sobremesa'), ('porcao', 'Porção'), ('combo', 'Combo'), ('pastel', 'Pastel')], default=True, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=produtos.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='produto',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
